package com.campuscon.repository;

import com.campuscon.model.AutoGeneratedGroup;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

@Repository
public interface AutoGeneratedGroupRepository extends JpaRepository<AutoGeneratedGroup, Long> {

    Optional<AutoGeneratedGroup> findByNameAndCollegeName(String name, String collegeName);
    boolean existsByNameAndCollegeName(String name, String collegeName);

    // For getting user's group
    List<AutoGeneratedGroup> findByMembersContaining(com.campuscon.model.User user);
}
