package com.campuscon.repository;

import com.campuscon.model.ChatGroup;
import com.campuscon.model.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

@Repository
public interface ChatGroupRepository extends JpaRepository<ChatGroup, Long> {
    List<ChatGroup> findByIsAutoGeneratedTrue();
    
    List<ChatGroup> findByMembersContaining(User user);
    
    Optional<ChatGroup> findByBatchYearAndCourseCodeAndCollegeName(String batchYear, String courseCode, String collegeName);
    
    @Query("SELECT g FROM ChatGroup g JOIN g.members m WHERE m = ?1 ORDER BY g.createdAt DESC")
    List<ChatGroup> findUserGroups(User user);
    
    boolean existsByNameAndCreator(String name, User creator);
}
