class ApiEndpoints {
  static const String baseUrl = 'https://api.campuscon.com/api';
  
  // Authentication endpoints
  static const String login = '$baseUrl/auth/login';
  static const String studentLogin = '$baseUrl/auth/student/login';
  static const String societyLogin = '$baseUrl/auth/society/login';
  
  // Registration endpoints
  static const String studentRegister = '$baseUrl/auth/student/register';
  static const String societyRegister = '$baseUrl/auth/society/register';
  
  // OTP verification
  static const String sendOtp = '$baseUrl/auth/otp/send';
  static const String verifyOtp = '$baseUrl/auth/otp/verify';
  
  // Token refresh
  static const String refreshToken = '$baseUrl/auth/token/refresh';

  // User profile
  static const String userProfile = '$baseUrl/user/profile';
  static const String updateProfile = '$baseUrl/user/profile/update';
  
  // University and College data
  static const String universities = '$baseUrl/auth/universities';
  static const String colleges = '$baseUrl/auth/colleges';
  static const String courses = '$baseUrl/data/courses';
  static const String validateEmailDomain = '$baseUrl/auth/validate-email-domain';
  
  // Deeds (society events)
  static const String deeds = '$baseUrl/deeds';
  static const String deedById = '$baseUrl/deeds'; // append /{id}
  static const String societyDeeds = '$baseUrl/deeds/society'; // append /{societyId}
  static const String collegeDeeds = '$baseUrl/deeds/college'; // append /{collegeName}
  static const String universityDeeds = '$baseUrl/deeds/university'; // append /{universityName}
  static const String upcomingDeeds = '$baseUrl/deeds/upcoming';
  static const String deedsByCategory = '$baseUrl/deeds/category'; // append /{category}
  static const String popularDeeds = '$baseUrl/deeds/popular';
  static const String deedLike = '$baseUrl/deeds'; // append /{id}/like
  static const String deedSave = '$baseUrl/deeds'; // append /{id}/save
  static const String deedComments = '$baseUrl/deeds'; // append /{id}/comments
  static const String deedShare = '$baseUrl/deeds'; // append /{id}/share
  
  // Bricks (student/society posts)
  static const String bricks = '$baseUrl/bricks';
  static const String brickById = '$baseUrl/bricks'; // append /{id}
  static const String bricksFeed = '$baseUrl/bricks/feed'; // bricks from bonded users
  static const String userBricks = '$baseUrl/bricks/user'; // append /{userId}
  static const String brickLike = '$baseUrl/bricks'; // append /{id}/like
  static const String brickComment = '$baseUrl/bricks'; // append /{id}/comment
  static const String brickComments = '$baseUrl/bricks'; // append /{id}/comments
  static const String brickSave = '$baseUrl/bricks'; // append /{id}/save
  static const String savedBricks = '$baseUrl/bricks/saved';
  static const String brickShare = '$baseUrl/bricks'; // append /{id}/share
  
  // Comments and Replies
  static const String deedCommentReplies = '$baseUrl/deeds/comments'; // append /{commentId}/replies
  static const String brickCommentReplies = '$baseUrl/bricks/comments'; // append /{commentId}/replies
  
  // Society Management
  static const String createDeed = '$baseUrl/deeds';
  static const String deedRegistration = '$baseUrl/deed-registration';
  static const String societySettings = '$baseUrl/society-settings';
  
  // Saved Items
  static const String savedItems = '$baseUrl/saved-items';
  
  // Auto-generated Groups and Messaging
  static const String autoGeneratedGroups = '$baseUrl/auto-generated-groups';
  static const String messages = '$baseUrl/messages';
  static const String createGroup = '$baseUrl/messages/group';
}