package com.campuscon.service;

import com.campuscon.dto.auth.AuthResponse;
import com.campuscon.dto.auth.LoginRequest;
import com.campuscon.dto.auth.RegisterRequest;
import com.campuscon.model.College;
import com.campuscon.model.CollegeDomainInfo;
import com.campuscon.model.University;
import com.campuscon.model.User;
import com.campuscon.repository.CollegeRepository;
import com.campuscon.repository.UniversityRepository;
import com.campuscon.repository.UserRepository;
import com.campuscon.security.JwtUtil;
import lombok.RequiredArgsConstructor;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Optional;
import java.util.Random;
import java.util.concurrent.TimeUnit;

@Service
@RequiredArgsConstructor
public class AuthService {
    private final UserRepository userRepository;
    private final UniversityRepository universityRepository;
    private final CollegeRepository collegeRepository;
    private final PasswordEncoder passwordEncoder;
    private final JwtUtil jwtUtil;
    private final AuthenticationManager authenticationManager;
    private final RedisTemplate<String, String> redisTemplate;
    private final EmailService emailService;
    private final CollegeDomainInfoService collegeDomainInfoService;
    private final AutoGeneratedGroupService autoGeneratedGroupService;

    @Transactional
    public AuthResponse register(RegisterRequest request) {
        // Validate if username or email already exists
        if (userRepository.existsByUsername(request.getUsername())) {
            throw new RuntimeException("Username already exists");
        }
        if (userRepository.existsByEmail(request.getEmail())) {
            throw new RuntimeException("Email already exists");
        }

        // Verify university and college
        University university = universityRepository.findByName(request.getUniversityName())
                .orElseThrow(() -> new RuntimeException("University not found"));

        College college = collegeRepository.findByNameAndUniversity(request.getCollegeName(), university)
                .orElseThrow(() -> new RuntimeException("College not found for the selected university"));

        // Verify email domain using the college domain info service
        String emailDomain = extractDomainFromEmail(request.getEmail());
        
        // Try to get college info from the enhanced service first
        boolean validDomain = collegeDomainInfoService.validateEmailDomain(
            request.getEmail(), 
            request.getCollegeName(),
            request.getUniversityName()
        );
        
        if (!validDomain) {
            // Fall back to the original validation if college domain info is not yet available
            String expectedDomain = college.getFullEmailDomain();
            if (!emailDomain.equalsIgnoreCase(expectedDomain)) {
                throw new RuntimeException("Email domain must be " + expectedDomain + " for the selected college");
            }
        }

        // Create new user
        User user = new User();
        
        if (request.isSociety()) {
            // Society registration
            if (request.getSocietyName() == null || request.getSocietyName().trim().isEmpty()) {
                throw new RuntimeException("Society name is required");
            }
            
            user.setUsername(request.getSocietyName()); // Society username is the society name
            user.setSocietyPresidentName(request.getSocietyPresidentName());
            user.setRole(User.UserRole.SOCIETY);
            user.setSociety(true);
        } else {
            // Student registration
            user.setUsername(request.getUsername());
            user.setRollNumber(request.getRollNumber());
            user.setRole(User.UserRole.STUDENT);
            user.setSociety(false);
            
            // Extract batch year and course code from roll number
            extractRollNumberInfo(user);
        }
        
        user.setEmail(request.getEmail());
        user.setPassword(passwordEncoder.encode(request.getPassword()));
        user.setUniversityName(request.getUniversityName());
        user.setCollegeName(request.getCollegeName());
        user.setEmailVerified(false);
        
        user = userRepository.save(user);

        // Generate and send OTP
        String otp = generateOTP();
        redisTemplate.opsForValue().set(
            "OTP:" + user.getEmail(),
            otp,
            10, // OTP valid for 10 minutes
            TimeUnit.MINUTES
        );

        // Send OTP via email
        emailService.sendOTPEmail(user.getEmail(), otp);

        return AuthResponse.builder()
                .username(user.getUsername())
                .email(user.getEmail())
                .role(user.getRole())
                .isVerified(false)
                .message("Registration successful. Please verify your email.")
                .build();
    }

    public AuthResponse login(LoginRequest request) {
        try {
            Authentication authentication = authenticationManager.authenticate(
                new UsernamePasswordAuthenticationToken(
                    request.getUsernameOrEmail(),
                    request.getPassword()
                )
            );

            User user = (User) authentication.getPrincipal();
            String token = jwtUtil.generateToken(user);

            return AuthResponse.builder()
                    .token(token)
                    .username(user.getUsername())
                    .email(user.getEmail())
                    .role(user.getRole())
                    .isVerified(user.isEmailVerified())
                    .message("Login successful")
                    .build();
        } catch (Exception e) {
            throw new RuntimeException("Invalid username/email or password");
        }
    }

    @Transactional
    public AuthResponse verifyOTP(String email, String otp) {
        String storedOTP = redisTemplate.opsForValue().get("OTP:" + email);
        if (storedOTP == null || !storedOTP.equals(otp)) {
            throw new RuntimeException("Invalid or expired OTP");
        }

        User user = userRepository.findByEmail(email)
                .orElseThrow(() -> new RuntimeException("User not found"));
        
        user.setEmailVerified(true);
        user = userRepository.save(user);

        // Delete OTP after successful verification
        redisTemplate.delete("OTP:" + email);

        // After email verification, assign user to auto-generated groups
        if (!user.isSociety()) {
            autoGeneratedGroupService.assignUserToAutoGroups(user);
        }

        String token = jwtUtil.generateToken(user);

        return AuthResponse.builder()
                .token(token)
                .username(user.getUsername())
                .email(user.getEmail())
                .role(user.getRole())
                .isVerified(true)
                .message("Email verified successfully")
                .build();
    }

    public AuthResponse verifySociety(String presidentEmail, String societyId) {
        User society = userRepository.findById(Long.parseLong(societyId))
                .orElseThrow(() -> new RuntimeException("Society not found"));
        
        if (!society.isSociety()) {
            throw new RuntimeException("This user is not a society");
        }
        
        if (!society.getSocietyPresidentName().equals(presidentEmail)) {
            throw new RuntimeException("Invalid president email for this society");
        }
        
        society.setEmailVerified(true);
        society = userRepository.save(society);
        
        return AuthResponse.builder()
                .username(society.getUsername())
                .email(society.getEmail())
                .role(society.getRole())
                .isVerified(true)
                .message("Society verified successfully")
                .build();
    }

    private String generateOTP() {
        Random random = new Random();
        int otp = 100000 + random.nextInt(900000); // 6-digit OTP
        return String.valueOf(otp);
    }

    private void extractRollNumberInfo(User user) {
        String rollNumber = user.getRollNumber();
        if (rollNumber == null || rollNumber.trim().isEmpty()) {
            return;
        }
        
        // Example roll number format: 24/cse/035
        // 24: Batch year (2024)
        // cse: Course code
        // 035: Student number
        try {
            String[] parts = rollNumber.split("/");
            if (parts.length >= 2) {
                user.setBatchYear(parts[0]);
                user.setCourseCode(parts[1]);
            }
        } catch (Exception e) {
            // If parsing fails, leave the fields null
        }
    }
    
    private String extractDomainFromEmail(String email) {
        return email.substring(email.indexOf('@') + 1);
    }

    /**
     * Attempt to get college and batch information from email domain
     * This is used to enhance the registration experience
     */
    public Optional<CollegeDomainInfo> getCollegeInfoFromEmail(String email) {
        return collegeDomainInfoService.getCollegeInfoFromEmail(email);
    }
}
