package com.campuscon.service;

import com.campuscon.model.AutoGeneratedGroup;
import com.campuscon.model.User;
import com.campuscon.repository.AutoGeneratedGroupRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Optional;
import java.util.List;

@Service
@RequiredArgsConstructor
@Slf4j
public class AutoGeneratedGroupService {

    private final AutoGeneratedGroupRepository autoGroupRepository;

    /**
     * Assign user only to batch + course specific group
     */
    @Transactional
    public void assignUserToAutoGroups(User user) {
        if (user.isSociety()) return;

        // Check all required fields
        if (user.getBatchYear() == null || user.getBatchYear().isEmpty()) return;
        if (user.getCourseCode() == null || user.getCourseCode().isEmpty()) return;
        if (user.getCollegeName() == null || user.getCollegeName().isEmpty()) return;
        if (user.getUniversityName() == null || user.getUniversityName().isEmpty()) return;

        ensureAndAddToBatchCourseGroup(user);
    }

    /**
     * Ensure course + batch specific group exists and add user
     */
    private void ensureAndAddToBatchCourseGroup(User user) {
        String batchYear = user.getBatchYear();
        String courseCode = user.getCourseCode();
        String collegeName = user.getCollegeName();
        String universityName = user.getUniversityName();

        String groupName = courseCode.toUpperCase() + " " + batchYear;
        String description = batchYear + " batch " + courseCode.toUpperCase() + " students at " + collegeName;

        Optional<AutoGeneratedGroup> existingGroup = autoGroupRepository.findByNameAndCollegeName(groupName, collegeName);

        AutoGeneratedGroup group = existingGroup.orElseGet(() -> {
            AutoGeneratedGroup newGroup = AutoGeneratedGroup.builder()
                    .name(groupName)
                    .description(description)
                    .type(AutoGeneratedGroup.GroupType.BATCH_COURSE_SPECIFIC)
                    .universityName(universityName)
                    .collegeName(collegeName)
                    .batchYear(batchYear)
                    .courseCode(courseCode)
                    .active(true)
                    .build();
            return autoGroupRepository.save(newGroup);
        });

        group.addMember(user);
        autoGroupRepository.save(group);
    }

    /**
     * Get all auto-generated groups a user belongs to
     */
    public List<AutoGeneratedGroup> getUserAutoGroups(User user) {
        return autoGroupRepository.findByMembersContaining(user);
    }
}
