package com.campuscon.service;

import com.campuscon.model.ChatGroup;
import com.campuscon.model.User;
import com.campuscon.repository.ChatGroupRepository;
import com.campuscon.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;
import java.util.Set;

@Service
@RequiredArgsConstructor
public class GroupService {
    private final ChatGroupRepository chatGroupRepository;
    private final UserRepository userRepository;
    private final RedisTemplate<String, Object> redisTemplate;

    /**
     * Creates or gets the auto-generated batch group for students based on batch, course, and college
     */
    public ChatGroup getOrCreateBatchGroup(String batchYear, String courseCode, String collegeName) {
        String cacheKey = "batch_group:" + collegeName + ":" + courseCode + ":" + batchYear;
        
        // Try to get from cache first
        ChatGroup cachedGroup = (ChatGroup) redisTemplate.opsForValue().get(cacheKey);
        if (cachedGroup != null) {
            return cachedGroup;
        }
        
        // Check if group already exists in database
        Optional<ChatGroup> existingGroup = chatGroupRepository.findByBatchYearAndCourseCodeAndCollegeName(
                batchYear, courseCode, collegeName);
        
        if (existingGroup.isPresent()) {
            ChatGroup group = existingGroup.get();
            // Cache the result
            redisTemplate.opsForValue().set(cacheKey, group);
            return group;
        }
        
        // Create a new auto-generated group
        ChatGroup newGroup = new ChatGroup();
        newGroup.setName(courseCode + " " + batchYear);
        newGroup.setBatchYear(batchYear);
        newGroup.setCourseCode(courseCode);
        newGroup.setCollegeName(collegeName);
        newGroup.setAutoGenerated(true);
        
        ChatGroup savedGroup = chatGroupRepository.save(newGroup);
        
        // Cache the newly created group
        redisTemplate.opsForValue().set(cacheKey, savedGroup);
        
        return savedGroup;
    }
    
    /**
     * Adds a user to the appropriate batch group based on their details
     */
    public void addUserToBatchGroup(User user) {
        if (user.getBatchYear() == null || user.getCourseCode() == null || user.getCollegeName() == null) {
            throw new RuntimeException("User batch, course, or college information is missing");
        }
        
        ChatGroup batchGroup = getOrCreateBatchGroup(user.getBatchYear(), user.getCourseCode(), user.getCollegeName());
        
        // Add user to the group if not already a member
        if (!batchGroup.getMembers().contains(user)) {
            batchGroup.getMembers().add(user);
            chatGroupRepository.save(batchGroup);
        }
    }
    
    /**
     * Creates a custom group with the given users
     */
    public ChatGroup createCustomGroup(String groupName, String groupImageUrl, Long creatorId, Set<Long> memberIds) {
        User creator = userRepository.findById(creatorId)
                .orElseThrow(() -> new RuntimeException("Creator user not found"));
        
        // Check if a group with this name already exists for this creator
        if (chatGroupRepository.existsByNameAndCreator(groupName, creator)) {
            throw new RuntimeException("You already have a group with this name");
        }
        
        ChatGroup newGroup = new ChatGroup();
        newGroup.setName(groupName);
        newGroup.setGroupImageUrl(groupImageUrl);
        newGroup.setCreator(creator);
        newGroup.setAutoGenerated(false);
        
        // Add creator to members
        newGroup.getMembers().add(creator);
        
        // Add other members
        if (memberIds != null && !memberIds.isEmpty()) {
            List<User> members = userRepository.findAllById(memberIds);
            newGroup.getMembers().addAll(members);
        }
        
        return chatGroupRepository.save(newGroup);
    }
    
    /**
     * Gets all groups that a user is a member of
     */
    public List<ChatGroup> getUserGroups(User user) {
        return chatGroupRepository.findUserGroups(user);
    }
    
    /**
     * Add a user to a group
     */
    public void addUserToGroup(Long groupId, Long userId) {
        ChatGroup group = chatGroupRepository.findById(groupId)
                .orElseThrow(() -> new RuntimeException("Group not found"));
        
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found"));
        
        if (group.isAutoGenerated()) {
            throw new RuntimeException("Cannot manually add users to auto-generated groups");
        }
        
        if (!group.getMembers().contains(user)) {
            group.getMembers().add(user);
            chatGroupRepository.save(group);
        }
    }
    
    /**
     * Remove a user from a group
     */
    public void removeUserFromGroup(Long groupId, Long userId) {
        ChatGroup group = chatGroupRepository.findById(groupId)
                .orElseThrow(() -> new RuntimeException("Group not found"));
        
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found"));
        
        if (group.isAutoGenerated()) {
            throw new RuntimeException("Cannot remove users from auto-generated groups");
        }
        
        if (group.getCreator().equals(user)) {
            throw new RuntimeException("Group creator cannot leave the group");
        }
        
        if (group.getMembers().contains(user)) {
            group.getMembers().remove(user);
            chatGroupRepository.save(group);
        }
    }
}
