package com.campuscon.service;

import com.campuscon.dto.message.MessageRequest;
import com.campuscon.dto.message.MessageResponse;
import com.campuscon.model.*;
import com.campuscon.repository.*;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class MessageService {
    private final UserRepository userRepository;
    private final ChatGroupRepository chatGroupRepository;
    private final GroupMessageRepository groupMessageRepository;
    private final DirectMessageRepository directMessageRepository;
    private final BondRepository bondRepository;
    
    /**
     * Save a direct message and returns the response DTO
     */
    @Transactional
    public MessageResponse saveDirectMessage(String senderEmail, Long receiverId, MessageRequest request) {
        User sender = userRepository.findByEmail(senderEmail)
                .orElseThrow(() -> new RuntimeException("Sender not found"));
                
        User receiver = userRepository.findById(receiverId)
                .orElseThrow(() -> new RuntimeException("Receiver not found"));
        
        // Check if users are bonded (required for direct messaging)
        if (!bondRepository.areUsersBonded(sender, receiver)) {
            throw new RuntimeException("Cannot send message to unbonded user");
        }
        
        DirectMessage message = new DirectMessage();
        message.setContent(request.getContent());
        message.setSender(sender);
        message.setReceiver(receiver);
        message.setRead(false);
        
        // Set reply reference if provided
        if (request.getReplyToId() != null) {
            DirectMessage replyToMessage = directMessageRepository.findById(request.getReplyToId())
                    .orElseThrow(() -> new RuntimeException("Reply message not found"));
            message.setReplyTo(replyToMessage);
        }
        
        DirectMessage savedMessage = directMessageRepository.save(message);
        
        // Convert to response DTO
        return convertToDirectMessageResponse(savedMessage);
    }
    
    /**
     * Save a group message and returns the response DTO
     */
    @Transactional
    public MessageResponse saveGroupMessage(String senderEmail, Long groupId, MessageRequest request) {
        User sender = userRepository.findByEmail(senderEmail)
                .orElseThrow(() -> new RuntimeException("Sender not found"));
                
        ChatGroup group = chatGroupRepository.findById(groupId)
                .orElseThrow(() -> new RuntimeException("Group not found"));
        
        // Verify sender is a member of the group
        if (!group.getMembers().contains(sender)) {
            throw new RuntimeException("User is not a member of this group");
        }
        
        // For non-auto-generated groups, verify if unbonded users need admin approval
        if (!group.isAutoGenerated() && sender != group.getCreator()) {
            // Check if sender is bonded with the group creator
            if (!bondRepository.areUsersBonded(sender, group.getCreator())) {
                throw new RuntimeException("Unbonded users need admin approval to send messages");
            }
        }
        
        GroupMessage message = new GroupMessage();
        message.setContent(request.getContent());
        message.setSender(sender);
        message.setGroup(group);
        
        // Add sender to readBy list (sender has read their own message)
        message.getReadBy().add(sender);
        
        // Set reply reference if provided
        if (request.getReplyToId() != null) {
            GroupMessage replyToMessage = groupMessageRepository.findById(request.getReplyToId())
                    .orElseThrow(() -> new RuntimeException("Reply message not found"));
            message.setReplyTo(replyToMessage);
        }
        
        GroupMessage savedMessage = groupMessageRepository.save(message);
        
        // Convert to response DTO
        return convertToGroupMessageResponse(savedMessage);
    }
    
    /**
     * Mark a message as read
     */
    @Transactional
    public void markMessageAsRead(Long messageId, String userEmail) {
        User user = userRepository.findByEmail(userEmail)
                .orElseThrow(() -> new RuntimeException("User not found"));
        
        // Try to find as direct message first
        directMessageRepository.findById(messageId).ifPresent(message -> {
            // Only mark as read if this user is the receiver
            if (message.getReceiver().equals(user)) {
                message.setRead(true);
                directMessageRepository.save(message);
            }
        });
        
        // If not a direct message, try as group message
        groupMessageRepository.findById(messageId).ifPresent(message -> {
            // Only mark as read if user is a member of the group and not the sender
            if (message.getGroup().getMembers().contains(user) && !message.getSender().equals(user)) {
                message.getReadBy().add(user);
                groupMessageRepository.save(message);
            }
        });
    }
    
    /**
     * Add a reaction to a message
     */
    @Transactional
    public MessageResponse addReaction(Long messageId, String userEmail, String reaction) {
        User user = userRepository.findByEmail(userEmail)
                .orElseThrow(() -> new RuntimeException("User not found"));
        
        // Try to find as direct message first
        DirectMessage directMessage = directMessageRepository.findById(messageId).orElse(null);
        if (directMessage != null) {
            // Verify user is either sender or receiver
            if (directMessage.getSender().equals(user) || directMessage.getReceiver().equals(user)) {
                directMessage.getReactions().add(reaction);
                DirectMessage savedMessage = directMessageRepository.save(directMessage);
                return convertToDirectMessageResponse(savedMessage);
            }
        }
        
        // If not a direct message, try as group message
        GroupMessage groupMessage = groupMessageRepository.findById(messageId).orElse(null);
        if (groupMessage != null) {
            // Verify user is a group member
            if (groupMessage.getGroup().getMembers().contains(user)) {
                groupMessage.getReactions().add(reaction);
                GroupMessage savedMessage = groupMessageRepository.save(groupMessage);
                return convertToGroupMessageResponse(savedMessage);
            }
        }
        
        return null;
    }
    
    /**
     * Get a paginated list of messages for a direct conversation
     */
    public List<MessageResponse> getDirectConversation(Long userId, Long otherUserId, int page, int size) {
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found"));
                
        User otherUser = userRepository.findById(otherUserId)
                .orElseThrow(() -> new RuntimeException("Other user not found"));
        
        // Check if users are bonded
        if (!bondRepository.areUsersBonded(user, otherUser)) {
            return Collections.emptyList();
        }
        
        Pageable pageable = PageRequest.of(page, size, Sort.by("sentAt").descending());
        Page<DirectMessage> messages = directMessageRepository.findActiveConversation(user, otherUser, pageable);
        
        return messages.getContent().stream()
                .map(this::convertToDirectMessageResponse)
                .collect(Collectors.toList());
    }
    
    /**
     * Get a paginated list of messages for a group
     */
    public List<MessageResponse> getGroupConversation(Long userId, Long groupId, int page, int size) {
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found"));
                
        ChatGroup group = chatGroupRepository.findById(groupId)
                .orElseThrow(() -> new RuntimeException("Group not found"));
        
        // Verify user is a group member
        if (!group.getMembers().contains(user)) {
            throw new RuntimeException("User is not a member of this group");
        }
        
        Pageable pageable = PageRequest.of(page, size, Sort.by("sentAt").descending());
        Page<GroupMessage> messages = groupMessageRepository.findActiveMessagesByGroup(group, pageable);
        
        return messages.getContent().stream()
                .map(this::convertToGroupMessageResponse)
                .collect(Collectors.toList());
    }
    
    /**
     * Get recipient ID for a direct message
     */
    public Long getRecipientId(Long messageId, String userEmail) {
        User user = userRepository.findByEmail(userEmail)
                .orElseThrow(() -> new RuntimeException("User not found"));
        
        DirectMessage directMessage = directMessageRepository.findById(messageId).orElse(null);
        if (directMessage != null) {
            if (directMessage.getSender().equals(user)) {
                return directMessage.getReceiver().getId();
            } else if (directMessage.getReceiver().equals(user)) {
                return directMessage.getSender().getId();
            }
        }
        
        return null;
    }
    
    /**
     * Get group ID for a group message
     */
    public Long getGroupId(Long messageId) {
        GroupMessage groupMessage = groupMessageRepository.findById(messageId).orElse(null);
        if (groupMessage != null) {
            return groupMessage.getGroup().getId();
        }
        
        return null;
    }
    
    /**
     * Delete a message (mark as deleted)
     */
    @Transactional
    public void deleteMessage(Long messageId, String userEmail) {
        User user = userRepository.findByEmail(userEmail)
                .orElseThrow(() -> new RuntimeException("User not found"));
        
        // Try to find as direct message first
        DirectMessage directMessage = directMessageRepository.findById(messageId).orElse(null);
        if (directMessage != null) {
            // Only allow sender to delete
            if (directMessage.getSender().equals(user)) {
                directMessage.setDeleted(true);
                directMessageRepository.save(directMessage);
                return;
            }
        }
        
        // If not a direct message, try as group message
        GroupMessage groupMessage = groupMessageRepository.findById(messageId).orElse(null);
        if (groupMessage != null) {
            // Allow sender or group creator to delete
            if (groupMessage.getSender().equals(user) || 
                groupMessage.getGroup().getCreator().equals(user)) {
                groupMessage.setDeleted(true);
                groupMessageRepository.save(groupMessage);
            }
        }
    }
    
    /**
     * Convert a direct message entity to DTO
     */
    private MessageResponse convertToDirectMessageResponse(DirectMessage message) {
        MessageResponse response = new MessageResponse();
        response.setId(message.getId());
        response.setContent(message.getContent());
        response.setSentAt(message.getSentAt());
        response.setRead(message.isRead());
        response.setPinned(message.isPinned());
        response.setReactions(message.getReactions());
        
        // Set sender info
        MessageResponse.UserDTO senderDTO = new MessageResponse.UserDTO();
        senderDTO.setId(message.getSender().getId());
        senderDTO.setUsername(message.getSender().getUsername());
        senderDTO.setProfilePictureUrl(message.getSender().getProfilePictureUrl());
        response.setSender(senderDTO);
        
        // Set reply info if exists
        if (message.getReplyTo() != null) {
            response.setReplyToId(message.getReplyTo().getId());
            response.setReplyToContent(message.getReplyTo().getContent());
        }
        
        return response;
    }
    
    /**
     * Convert a group message entity to DTO
     */
    private MessageResponse convertToGroupMessageResponse(GroupMessage message) {
        MessageResponse response = new MessageResponse();
        response.setId(message.getId());
        response.setContent(message.getContent());
        response.setSentAt(message.getSentAt());
        
        // For group messages, isRead is true if the user has read it
        // This will be handled by the client when receiving the message
        response.setRead(false);
        
        response.setPinned(message.isPinned());
        response.setReactions(message.getReactions());
        
        // Set sender info
        MessageResponse.UserDTO senderDTO = new MessageResponse.UserDTO();
        senderDTO.setId(message.getSender().getId());
        senderDTO.setUsername(message.getSender().getUsername());
        senderDTO.setProfilePictureUrl(message.getSender().getProfilePictureUrl());
        response.setSender(senderDTO);
        
        // Set reply info if exists
        if (message.getReplyTo() != null) {
            response.setReplyToId(message.getReplyTo().getId());
            response.setReplyToContent(message.getReplyTo().getContent());
        }
        
        return response;
    }
}
