package com.campuscon.controller;

import com.campuscon.dto.ApiResponse;
import com.campuscon.model.AutoGeneratedGroup;
import com.campuscon.model.User;
import com.campuscon.service.AutoGeneratedGroupService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/auto-groups")
@RequiredArgsConstructor
public class AutoGeneratedGroupController {

    private final AutoGeneratedGroupService autoGroupService;

    @GetMapping("/my-groups")
    public ResponseEntity<ApiResponse<List<AutoGeneratedGroup>>> getMyAutoGroups(
            @AuthenticationPrincipal User user) {

        List<AutoGeneratedGroup> groups = autoGroupService.getUserAutoGroups(user);
        return ResponseEntity.ok(ApiResponse.success(groups, "User's auto-generated group retrieved successfully"));
    }
}
