package com.campuscon.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

@Entity
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AutoGeneratedGroup {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    private String name;
    private String description;
    
    @Enumerated(EnumType.STRING)
    private GroupType type;
    
    private String universityName;
    private String collegeName;
    private String batchYear;
    private String courseCode;
    
    private LocalDateTime createdAt;
    private boolean active;
    
    @ManyToMany
    @JoinTable(
        name = "auto_group_members",
        joinColumns = @JoinColumn(name = "group_id"),
        inverseJoinColumns = @JoinColumn(name = "user_id")
    )
    @Builder.Default
    private Set<User> members = new HashSet<>();
    
    public enum GroupType {
        UNIVERSITY_WIDE,      // All students from a university
        COLLEGE_WIDE,         // All students from a specific college
        BATCH_WIDE,           // All students from a specific batch
        COURSE_WIDE,          // All students from a specific course
        BATCH_COURSE_SPECIFIC // Students from specific batch and course
    }

    @PrePersist
    public void prePersist() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
    }
    
    public void addMember(User user) {
        members.add(user);
    }
    
    public void removeMember(User user) {
        members.remove(user);
    }
}
